### This workflow has access to secrets and a read-write token
name: Publish
on:
  workflow_run:
    branches: [master]
    types: [completed]
    workflows: [CI]

jobs:
  # Why do we need to build here as well as in the main CI pipeline? Because the actions/download-artifact action
  # doesn't allow you to download artifacts from other workflows, despite GitHub pushing that as the recommended
  # work-around for Dependabot permissions. See: https://github.com/actions/download-artifact/issues/60
  build:
    runs-on: ubuntu-latest
    name: Build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 22.13.1
          cache: yarn
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build
          path: lib

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 22.13.1
          cache: yarn
      - run: yarn install
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build
          path: lib
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: yarn semantic-release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
